---
- name: This is my texy playbook
  hosts: all
  become: yes

  tasks:
  - name: Installing multiple packages
    yum:
      name: ['git', 'mysql' , 'tree' , 'httpd' , 'wget' , 'which']
      state: installed
      

